version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: npm build
  test:
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout
      - run: echo "testing the components"
      - run: npm install
      - run: npm install --only=dev
      - run: npm test
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test
        
